package dev.hafnium.monitoring.engine;

import dev.hafnium.monitoring.domain.Alert;
import dev.hafnium.monitoring.domain.Alert.Severity;
import dev.hafnium.monitoring.domain.Transaction;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import org.springframework.stereotype.Component;

/**
 * Rule engine for transaction monitoring.
 *
 * <p>
 * Evaluates transactions against a set of predefined rules to detect suspicious
 * activity. Rules
 * are defined declaratively and can be extended without code changes.
 */
@Component
public class RuleEngine {

    private final List<Rule> rules = new ArrayList<>();

    public RuleEngine() {
        initializeDefaultRules();
    }

    /**
     * Evaluates a transaction against all rules.
     *
     * @param transaction The transaction to evaluate
     * @return List of alerts generated by triggered rules
     */
    public List<Alert> evaluate(Transaction transaction) {
        List<Alert> alerts = new ArrayList<>();

        for (Rule rule : rules) {
            RuleResult result = rule.evaluate(transaction);
            if (result.triggered()) {
                Alert alert = createAlert(transaction, rule, result);
                alerts.add(alert);
            }
        }

        return alerts;
    }

    private Alert createAlert(Transaction transaction, Rule rule, RuleResult result) {
        Alert alert = new Alert();
        alert.setTenantId(transaction.getTenantId());
        alert.setCustomerId(transaction.getCustomerId());
        alert.setTxnId(transaction.getTxnId());
        alert.setRuleId(rule.id());
        alert.setRuleName(rule.name());
        alert.setSeverity(rule.severity());
        alert.setScore(BigDecimal.valueOf(result.score()));
        alert.setExplanation(result.explanation());
        alert.setTriggeredConditions(result.conditions());
        return alert;
    }

    /** Initializes default monitoring rules. */
    private void initializeDefaultRules() {
        // High-value transaction rule
        rules.add(
                new Rule(
                        "RULE-001",
                        "High Value Transaction",
                        "Transactions exceeding threshold amount",
                        Severity.MEDIUM,
                        txn -> {
                            BigDecimal threshold = new BigDecimal("10000");
                            if (txn.getAmount().compareTo(threshold) > 0) {
                                return new RuleResult(
                                        true,
                                        0.7,
                                        "Transaction amount exceeds threshold",
                                        Map.of(
                                                "condition", "amount > 10000",
                                                "actual_value", txn.getAmount().toString(),
                                                "threshold", threshold.toString()));
                            }
                            return RuleResult.NOT_TRIGGERED;
                        }));

        // Rapid succession transactions
        rules.add(
                new Rule(
                        "RULE-002",
                        "Velocity Threshold",
                        "Multiple transactions in short time period",
                        Severity.HIGH,
                        txn -> {
                            // This is a placeholder - actual implementation would check velocity
                            return RuleResult.NOT_TRIGGERED;
                        }));

        // High-risk geography
        rules.add(
                new Rule(
                        "RULE-003",
                        "High Risk Geography",
                        "Transaction involving high-risk jurisdiction",
                        Severity.HIGH,
                        txn -> {
                            if (txn.getGeoData() != null) {
                                String country = (String) txn.getGeoData().get("country");
                                // Sample high-risk countries for demonstration
                                List<String> highRiskCountries = List.of("XX", "YY", "ZZ");
                                if (country != null && highRiskCountries.contains(country.toUpperCase())) {
                                    return new RuleResult(
                                            true,
                                            0.8,
                                            "Transaction involves high-risk jurisdiction",
                                            Map.of(
                                                    "condition", "country in high_risk_list",
                                                    "actual_value", country,
                                                    "threshold", "high_risk_countries"));
                                }
                            }
                            return RuleResult.NOT_TRIGGERED;
                        }));

        // Unusual channel for customer
        rules.add(
                new Rule(
                        "RULE-004",
                        "Unusual Channel",
                        "Transaction through unusual channel for customer",
                        Severity.LOW,
                        txn -> {
                            // Placeholder - would check customer's typical channels
                            return RuleResult.NOT_TRIGGERED;
                        }));

        // Round amount structuring detection
        rules.add(
                new Rule(
                        "RULE-005",
                        "Structuring Detection",
                        "Transaction appears structured to avoid reporting",
                        Severity.HIGH,
                        txn -> {
                            BigDecimal amount = txn.getAmount();
                            BigDecimal reportingThreshold = new BigDecimal("10000");
                            BigDecimal structuringRange = new BigDecimal("500");

                            // Check if amount is just below reporting threshold
                            if (amount.compareTo(reportingThreshold.subtract(structuringRange)) >= 0
                                    && amount.compareTo(reportingThreshold) < 0) {
                                return new RuleResult(
                                        true,
                                        0.75,
                                        "Transaction amount appears structured below reporting threshold",
                                        Map.of(
                                                "condition", "amount in structuring_range",
                                                "actual_value", amount.toString(),
                                                "threshold", reportingThreshold.toString()));
                            }
                            return RuleResult.NOT_TRIGGERED;
                        }));
    }

    /**
     * Represents a monitoring rule.
     *
     * @param id          Rule identifier
     * @param name        Rule display name
     * @param description Rule description
     * @param severity    Default severity for alerts
     * @param evaluator   The evaluation function
     */
    public record Rule(
            String id,
            String name,
            String description,
            Severity severity,
            RuleEvaluator evaluator) {

        public RuleResult evaluate(Transaction transaction) {
            return evaluator.evaluate(transaction);
        }
    }

    /** Functional interface for rule evaluation. */
    @FunctionalInterface
    public interface RuleEvaluator {
        RuleResult evaluate(Transaction transaction);
    }

    /**
     * Represents the result of a rule evaluation.
     *
     * @param triggered   Whether the rule was triggered
     * @param score       Confidence score (0.0 to 1.0)
     * @param explanation Human-readable explanation
     * @param conditions  Map of triggered conditions with values
     */
    public record RuleResult(
            boolean triggered, double score, String explanation, Map<String, Object> conditions) {

        public static final RuleResult NOT_TRIGGERED = new RuleResult(false, 0.0, "", Map.of());
    }
}
